GET http://localhost:5000/api/skills

###

POST http://localhost:5000/api/users
Content-Type: application/json

{
    "email": "mueller.florian94@outlook.com",
    "username": "testusr",
    "password": "tst445"
}

###

POST http://localhost:5000/api/messages
Content-Type: application/json

{
    "email": "test@mail.xy"
}
